php7-web-dev:
  build: .
  restart: always
  ports:
    - "80:80"
    - "443:443"
  links:
     - mysql:mysql-server
  volumes:
    - ./website:/var/www/html
    - ./logs:/var/log/apache2

mysql:
  image: mysql
  restart: always
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
  volumes:
    - ./db:/var/lib/mysql

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  links:
    - mysql:db
  ports:
    - "8080:80"